server:
  port: 8761

spring:
  application:
    name: sc-eureka
  security:
    user:
      name: cab
      password: cab19891023

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/

