server:
  port: 8861

spring:
  application:
    name: gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000

user-service:
  ribbon:
    ReadTimeout: 10000
    ConnectTimeout: 10000

#超时配置说明：
#如果路由方式是serviceId的方式，配置为：zuul:routes:order:serviceId，那么ribbon的超时配置生效（user-service:ribbon:ReadTimeout）
#如果如果是url的方式，配置为：zuul:routes:user:url，则zuul.host开头的生效。
