spring:
  redis:
    host: 10.11.0.100
    port: 6379
    database: 0
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      #默认过滤器
      default-filters:
#      #是否忽略匹配前缀
#      - StripPrefix=1
      #限流过滤器
      - name: RequestRateLimiter
        args:
          key-resolver: '#{@hostAddrKeyResolver}'
          redis-rate-limiter.replenishRate: 1500
          redis-rate-limiter.burstCapacity: 3000
      #熔断过滤器
      - name: Hystrix
        args:
          name: fallbackcmd
          fallbackUri: forward:/defaultfallback
      #自定义过滤器，登陆过滤器
      - Authorize=true
      routes:
      #------------------------------------------------------------------------
      - id: user
        uri: lb://sc-service-user
        predicates:
        - Path=/user/**
        filters:
        #是否忽略匹配前缀
        - StripPrefix=0
#        #限流过滤器
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@hostAddrKeyResolver}'
#            redis-rate-limiter.replenishRate: 1500
#            redis-rate-limiter.burstCapacity: 3000
#        #熔断过滤器
#        - name: Hystrix
#          args:
#            name: fallbackcmd
#            fallbackUri: forward:/defaultfallback
#        #自定义过滤器，登陆过滤器
#        - Authorize=true


      #------------------------------------------------------------------------
      - id: 163                     #网关路由到网易官网
        uri: http://www.163.com/
        predicates:
        - Path=/163/**

#熔断器配置
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 3000
  shareSecurityContext: true


eureka:
  client:
    serviceUrl:
      defaultZone: http://cab:cab19891023@localhost:8761/eureka/


#网关日志输出
logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
