server:
  port: 8863

spring:
  application:
    name: sc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: user
        uri: lb://user-client
        predicates:
        - Path=/user/**
        filters:
        - StripPrefix=0


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
