spring:
  application:
    name: sc-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/chenanbing/sc-config-file.git
          search-paths: /user
#          search-paths:
#          - user
      label: master
      username: chenanbing
      password: cab19891023

server:
  port: 8862

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
