server:
  port: 8762
spring:
  application:
    name: sc-config


#  本地配置
  profiles:
    active: native,dev #默认启动的环境
  cloud:
    config:
      server:
        native:
          search-locations: classpath:properties/ # 搜索src/main/resource 下的properties文件夹下的文件


#  git配置
#  profiles:
#    active: dev #默认启动的环境
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/chenanbing/sc-config-file.git
#          search-paths: /user
#      label: master
#      username: chenanbing
#      password: cab19891023
