server:
  port: 8763

spring:
  application:
    name: user-service
  # amqp配置（stream也可用）
  rabbitmq:
    host: 10.11.0.100
    port: 5672
    username: cab
    password: cab19891023
    virtual-host: test
  # stream 配置
  cloud:
    stream:
      binders:
        test:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.11.0.100
                port: 5672
                username: cab
                password: cab19891023
                virtual-host: test
      bindings:
        input1:
          destination: tttt
          group: inputGroup
        input2:
          destination: tttt2
          group: inputGroup
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

