spring:
  # amqp配置（stream也可用）
  rabbitmq:
    host: 10.11.0.100
    port: 5672
    username: cab
    password: cab19891023
    virtual-host: test
  # stream 配置
  cloud:
    stream:
      binders:
        test:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 10.11.0.100
                port: 5672
                username: cab
                password: cab19891023
                virtual-host: test
      bindings:
        input1:
          destination: exchange1
          group: inputGroup
        input2:
          destination: exchange2
          group: inputGroup
        output3:
          destination: exchange3
          contentType: application/json #约定消息的内容编码格式
        input3:
          destination: exchange3
          group: inputGroup
eureka:
  client:
    serviceUrl:
      defaultZone: http://cab:cab19891023@localhost:8761/eureka/

